version: "3.7"

services:
  customer-web:
    image: registry.gitlab.com/maxsolutionsco/innov/innov-client:staging
    container_name: msc-customer-web
    networks:
      - msc-customer-network
    depends_on:
      - customer-db
    environment:
      USER: odoo
      PASSWORD: odoo 
      HOST: customer-db
    ports:
      - "6069:8069"
    volumes:
#     Comment line mnt for use local o development environment
#      - /mnt/api_msc_data/config/web:/etc/odoo
      - msc-customer-web-data:/var/lib/odoo
  customer-db:
    image: postgres:10
    container_name: msc-customer-db
    networks:
      - msc-customer-network
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - msc-customer-db-data:/var/lib/postgresql/data/pgdata
networks: 
  msc-customer-network:
    name: msc-customer-network
volumes:
  msc-customer-web-data:
    name: msc-customer-web-data
  msc-customer-db-data:
    name: msc-customer-db-data
