version: "3"

services:
  app:
    build: .
    container_name: innov_ce_web
    depends_on:
      - db
    environment:
      USER: odoo
      PASSWORD: odoo
      HOST: db
    ports:
      - "8069:8069"
    volumes:
      - ./:/mnt/extra-addons
      - innov-ce-web-data:/var/lib/odoo
  db:
    container_name: innov_ce_db
    image: postgres:9.5-alpine
    restart: always
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - innov-ce-db-data:/var/lib/postgresql/data/pgdata
volumes:
  innov-ce-web-data:
  innov-ce-db-data: