FROM registry.gitlab.com/maxsolutionsco/innov/innov-server

USER root

RUN set -x; \
        apt-get update \
        && apt-get install -y --no-install-recommends \
            git \ 
            vim \
            python3-setuptools

# Install some deps python.
ARG innov_client_path_addons=/mnt/innov-client
RUN mkdir -p ${innov_client_path_addons} && chown -R odoo ${innov_client_path_addons}

COPY innovt_cfdi_data ${path_addons}/innovt_cfdi_data
COPY innovt_client ${path_addons}/innovt_client
COPY innovt_invoice ${path_addons}/innovt_invoice
COPY innovt_payment ${path_addons}/innovt_payment

COPY requirements.txt ${innov_client_path_addons}requirements.txt

RUN pip3 install --no-cache-dir --upgrade pip -r ${innov_client_path_addons}/requirements.txt

# Expose Odoo services
EXPOSE 8069 8071

# Set the default config file
ENV ODOO_RC /etc/odoo/odoo.conf

USER odoo

ENTRYPOINT ["/entrypoint.sh"]
CMD ["odoo"]